//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TiagoUnity
{
    [Serializable]
    public class PickPlaceServiceRequest : Message
    {
        public const string k_RosMessageName = "tiago_unity/PickPlaceService";
        public override string RosMessageName => k_RosMessageName;

        public double[] joint_angles;
        public Geometry.PoseMsg pick_pose;
        public Geometry.PoseMsg place_pose;

        public PickPlaceServiceRequest()
        {
            this.joint_angles = new double[0];
            this.pick_pose = new Geometry.PoseMsg();
            this.place_pose = new Geometry.PoseMsg();
        }

        public PickPlaceServiceRequest(double[] joint_angles, Geometry.PoseMsg pick_pose, Geometry.PoseMsg place_pose)
        {
            this.joint_angles = joint_angles;
            this.pick_pose = pick_pose;
            this.place_pose = place_pose;
        }

        public static PickPlaceServiceRequest Deserialize(MessageDeserializer deserializer) => new PickPlaceServiceRequest(deserializer);

        private PickPlaceServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_angles, sizeof(double), deserializer.ReadLength());
            this.pick_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.place_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.joint_angles);
            serializer.Write(this.joint_angles);
            serializer.Write(this.pick_pose);
            serializer.Write(this.place_pose);
        }

        public override string ToString()
        {
            return "PickPlaceServiceRequest: " +
            "\njoint_angles: " + System.String.Join(", ", joint_angles.ToList()) +
            "\npick_pose: " + pick_pose.ToString() +
            "\nplace_pose: " + place_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
