//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.MoveBase
{
    [Serializable]
    public class MoveBaseActionGoalMsg : Message
    {
        public const string k_RosMessageName = "move_base_msgs/MoveBaseActionGoal";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public HeaderMsg header;
        public Actionlib.GoalIDMsg goal_id;
        public MoveBaseGoalMsg goal;

        public MoveBaseActionGoalMsg()
        {
            this.header = new HeaderMsg();
            this.goal_id = new Actionlib.GoalIDMsg();
            this.goal = new MoveBaseGoalMsg();
        }

        public MoveBaseActionGoalMsg(HeaderMsg header, Actionlib.GoalIDMsg goal_id, MoveBaseGoalMsg goal)
        {
            this.header = header;
            this.goal_id = goal_id;
            this.goal = goal;
        }

        public static MoveBaseActionGoalMsg Deserialize(MessageDeserializer deserializer) => new MoveBaseActionGoalMsg(deserializer);

        private MoveBaseActionGoalMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.goal_id = Actionlib.GoalIDMsg.Deserialize(deserializer);
            this.goal = MoveBaseGoalMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.goal_id);
            serializer.Write(this.goal);
        }

        public override string ToString()
        {
            return "MoveBaseActionGoalMsg: " +
            "\nheader: " + header.ToString() +
            "\ngoal_id: " + goal_id.ToString() +
            "\ngoal: " + goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
