//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.MoveBase
{
    [Serializable]
    public class MoveBaseActionResultMsg : Message
    {
        public const string k_RosMessageName = "move_base_msgs/MoveBaseActionResult";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public HeaderMsg header;
        public Actionlib.GoalStatusMsg status;
        public MoveBaseResultMsg result;

        public MoveBaseActionResultMsg()
        {
            this.header = new HeaderMsg();
            this.status = new Actionlib.GoalStatusMsg();
            this.result = new MoveBaseResultMsg();
        }

        public MoveBaseActionResultMsg(HeaderMsg header, Actionlib.GoalStatusMsg status, MoveBaseResultMsg result)
        {
            this.header = header;
            this.status = status;
            this.result = result;
        }

        public static MoveBaseActionResultMsg Deserialize(MessageDeserializer deserializer) => new MoveBaseActionResultMsg(deserializer);

        private MoveBaseActionResultMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.status = Actionlib.GoalStatusMsg.Deserialize(deserializer);
            this.result = MoveBaseResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.status);
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "MoveBaseActionResultMsg: " +
            "\nheader: " + header.ToString() +
            "\nstatus: " + status.ToString() +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
