//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveBase
{
    [Serializable]
    public class MoveBaseGoalMsg : Message
    {
        public const string k_RosMessageName = "move_base_msgs/MoveBaseGoal";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public Geometry.PoseStampedMsg target_pose;

        public MoveBaseGoalMsg()
        {
            this.target_pose = new Geometry.PoseStampedMsg();
        }

        public MoveBaseGoalMsg(Geometry.PoseStampedMsg target_pose)
        {
            this.target_pose = target_pose;
        }

        public static MoveBaseGoalMsg Deserialize(MessageDeserializer deserializer) => new MoveBaseGoalMsg(deserializer);

        private MoveBaseGoalMsg(MessageDeserializer deserializer)
        {
            this.target_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_pose);
        }

        public override string ToString()
        {
            return "MoveBaseGoalMsg: " +
            "\ntarget_pose: " + target_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
