//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveBase
{
    [Serializable]
    public class MoveBaseFeedbackMsg : Message
    {
        public const string k_RosMessageName = "move_base_msgs/MoveBaseFeedback";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public Geometry.PoseStampedMsg base_position;

        public MoveBaseFeedbackMsg()
        {
            this.base_position = new Geometry.PoseStampedMsg();
        }

        public MoveBaseFeedbackMsg(Geometry.PoseStampedMsg base_position)
        {
            this.base_position = base_position;
        }

        public static MoveBaseFeedbackMsg Deserialize(MessageDeserializer deserializer) => new MoveBaseFeedbackMsg(deserializer);

        private MoveBaseFeedbackMsg(MessageDeserializer deserializer)
        {
            this.base_position = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.base_position);
        }

        public override string ToString()
        {
            return "MoveBaseFeedbackMsg: " +
            "\nbase_position: " + base_position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
