//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TiagoHoloDt
{
    [Serializable]
    public class PlannedActionWithTypeAndArmMsg : Message
    {
        public const string k_RosMessageName = "tiago_holo_dt/PlannedActionWithTypeAndArm";
        public override string RosMessageName => k_RosMessageName;

        public bool planning_result;
        public string planning_arm;
        public string action_type;
        public PlannedActionMsg planned_action;

        public PlannedActionWithTypeAndArmMsg()
        {
            this.planning_result = false;
            this.planning_arm = "";
            this.action_type = "";
            this.planned_action = new PlannedActionMsg();
        }

        public PlannedActionWithTypeAndArmMsg(bool planning_result, string planning_arm, string action_type, PlannedActionMsg planned_action)
        {
            this.planning_result = planning_result;
            this.planning_arm = planning_arm;
            this.action_type = action_type;
            this.planned_action = planned_action;
        }

        public static PlannedActionWithTypeAndArmMsg Deserialize(MessageDeserializer deserializer) => new PlannedActionWithTypeAndArmMsg(deserializer);

        private PlannedActionWithTypeAndArmMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.planning_result);
            deserializer.Read(out this.planning_arm);
            deserializer.Read(out this.action_type);
            this.planned_action = PlannedActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.planning_result);
            serializer.Write(this.planning_arm);
            serializer.Write(this.action_type);
            serializer.Write(this.planned_action);
        }

        public override string ToString()
        {
            return "PlannedActionWithTypeAndArmMsg: " +
            "\nplanning_result: " + planning_result.ToString() +
            "\nplanning_arm: " + planning_arm.ToString() +
            "\naction_type: " + action_type.ToString() +
            "\nplanned_action: " + planned_action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
