//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TiagoHoloDt
{
    [Serializable]
    public class ActionServiceResponse : Message
    {
        public const string k_RosMessageName = "tiago_holo_dt/ActionService";
        public override string RosMessageName => k_RosMessageName;

        public bool planning_result;
        public PlannedActionMsg planned_action;

        public ActionServiceResponse()
        {
            this.planning_result = false;
            this.planned_action = new PlannedActionMsg();
        }

        public ActionServiceResponse(bool planning_result, PlannedActionMsg planned_action)
        {
            this.planning_result = planning_result;
            this.planned_action = planned_action;
        }

        public static ActionServiceResponse Deserialize(MessageDeserializer deserializer) => new ActionServiceResponse(deserializer);

        private ActionServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.planning_result);
            this.planned_action = PlannedActionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.planning_result);
            serializer.Write(this.planned_action);
        }

        public override string ToString()
        {
            return "ActionServiceResponse: " +
            "\nplanning_result: " + planning_result.ToString() +
            "\nplanned_action: " + planned_action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
