//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TiagoHoloDt
{
    [Serializable]
    public class ActionServiceRequest : Message
    {
        public const string k_RosMessageName = "tiago_holo_dt/ActionService";
        public override string RosMessageName => k_RosMessageName;

        public string action_type;
        public double[] joint_angles;
        public Geometry.PointMsg pick_pos;
        public Geometry.PointMsg place_pos;
        public Geometry.Vector3Msg grasp_direction;

        public ActionServiceRequest()
        {
            this.action_type = "";
            this.joint_angles = new double[0];
            this.pick_pos = new Geometry.PointMsg();
            this.place_pos = new Geometry.PointMsg();
            this.grasp_direction = new Geometry.Vector3Msg();
        }

        public ActionServiceRequest(string action_type, double[] joint_angles, Geometry.PointMsg pick_pos, Geometry.PointMsg place_pos, Geometry.Vector3Msg grasp_direction)
        {
            this.action_type = action_type;
            this.joint_angles = joint_angles;
            this.pick_pos = pick_pos;
            this.place_pos = place_pos;
            this.grasp_direction = grasp_direction;
        }

        public static ActionServiceRequest Deserialize(MessageDeserializer deserializer) => new ActionServiceRequest(deserializer);

        private ActionServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.action_type);
            deserializer.Read(out this.joint_angles, sizeof(double), deserializer.ReadLength());
            this.pick_pos = Geometry.PointMsg.Deserialize(deserializer);
            this.place_pos = Geometry.PointMsg.Deserialize(deserializer);
            this.grasp_direction = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_type);
            serializer.WriteLength(this.joint_angles);
            serializer.Write(this.joint_angles);
            serializer.Write(this.pick_pos);
            serializer.Write(this.place_pos);
            serializer.Write(this.grasp_direction);
        }

        public override string ToString()
        {
            return "ActionServiceRequest: " +
            "\naction_type: " + action_type.ToString() +
            "\njoint_angles: " + System.String.Join(", ", joint_angles.ToList()) +
            "\npick_pos: " + pick_pos.ToString() +
            "\nplace_pos: " + place_pos.ToString() +
            "\ngrasp_direction: " + grasp_direction.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
