//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TiagoHoloDt
{
    [Serializable]
    public class ExecutionServiceResponse : Message
    {
        public const string k_RosMessageName = "tiago_holo_dt/ExecutionService";
        public override string RosMessageName => k_RosMessageName;

        public bool execution_result;

        public ExecutionServiceResponse()
        {
            this.execution_result = false;
        }

        public ExecutionServiceResponse(bool execution_result)
        {
            this.execution_result = execution_result;
        }

        public static ExecutionServiceResponse Deserialize(MessageDeserializer deserializer) => new ExecutionServiceResponse(deserializer);

        private ExecutionServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.execution_result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.execution_result);
        }

        public override string ToString()
        {
            return "ExecutionServiceResponse: " +
            "\nexecution_result: " + execution_result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
