//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TiagoHoloDt
{
    [Serializable]
    public class JointStateServiceResponse : Message
    {
        public const string k_RosMessageName = "tiago_holo_dt/JointStateService";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.JointStateMsg robot_state;

        public JointStateServiceResponse()
        {
            this.robot_state = new Sensor.JointStateMsg();
        }

        public JointStateServiceResponse(Sensor.JointStateMsg robot_state)
        {
            this.robot_state = robot_state;
        }

        public static JointStateServiceResponse Deserialize(MessageDeserializer deserializer) => new JointStateServiceResponse(deserializer);

        private JointStateServiceResponse(MessageDeserializer deserializer)
        {
            this.robot_state = Sensor.JointStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_state);
        }

        public override string ToString()
        {
            return "JointStateServiceResponse: " +
            "\nrobot_state: " + robot_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
