//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TiagoHoloDt
{
    [Serializable]
    public class JointStateServiceRequest : Message
    {
        public const string k_RosMessageName = "tiago_holo_dt/JointStateService";
        public override string RosMessageName => k_RosMessageName;

        public bool data;

        public JointStateServiceRequest()
        {
            this.data = false;
        }

        public JointStateServiceRequest(bool data)
        {
            this.data = data;
        }

        public static JointStateServiceRequest Deserialize(MessageDeserializer deserializer) => new JointStateServiceRequest(deserializer);

        private JointStateServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "JointStateServiceRequest: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
