//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TiagoHoloDt
{
    [Serializable]
    public class PoseServiceResponse : Message
    {
        public const string k_RosMessageName = "tiago_holo_dt/PoseService";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg base_link_pose;

        public PoseServiceResponse()
        {
            this.base_link_pose = new Geometry.PoseMsg();
        }

        public PoseServiceResponse(Geometry.PoseMsg base_link_pose)
        {
            this.base_link_pose = base_link_pose;
        }

        public static PoseServiceResponse Deserialize(MessageDeserializer deserializer) => new PoseServiceResponse(deserializer);

        private PoseServiceResponse(MessageDeserializer deserializer)
        {
            this.base_link_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.base_link_pose);
        }

        public override string ToString()
        {
            return "PoseServiceResponse: " +
            "\nbase_link_pose: " + base_link_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
